### ISSUE TITLE
缺少jar包

### ISSUE THREAD

**Issue by HaimmingYu** [kongzhidea/pay#1]
<dependency>
            <groupId>com.alipay.api</groupId>
            <artifactId>alipay-sdk</artifactId>
            <version>1.5</version>
        </dependency>

**Comment by kongzhidea** [comment]
此jar包 在中央仓库好像没有，需要自己install到本地，或者deploy到自己的mvn私服。
具体jar包可以到 target目录下 找到此jar包，也可以从阿里官方文档中找到此jar包。

**Comment by TonyYule** [comment]
你可以放到WEB-INF发布上来吗

**Comment by TonyYule** [comment]
<dependency>
            <groupId>org.springside</groupId>
            <artifactId>springside-core</artifactId>
            <version>4.0.0.GA</version>
        </dependency>
这个也没有

**Comment by TonyYule** [comment]
<dependency>
            <groupId>net.sourceforge.pinyin4j</groupId>
            <artifactId>pinyin4j</artifactId>
            <version>2.5.0</version>
        </dependency>
还有这个

**Comment by kongzhidea** [comment]
https://github.com/kongzhidea/pay/tree/master/pay/target/pay/WEB-INF/lib

**Comment by kongzhidea** [comment]
pinyin4j 这个jar包 应该没有用到， pom里面去掉应该没有什么影响。
