### ISSUE TITLE
运行起来 其他页面在哪里呢

### ISSUE THREAD

**Issue by HaimmingYu** [kongzhidea/pay#2]
运行起来 页面只有
pay.index
其他支付宝 微信 怎么访问呢

**Comment by kongzhidea** [comment]
这个需要到各个controller里面找到对应到类，然后拼上链接和参数了， 因为这个只是我自己调试微信和支付宝接口使用的，所以就简单了一点。
另外如果测试微信和支付宝支付，需要提前 申请微信公众号支付权限，开通微信支付和支付宝支付商户才行。这个 需要一些企业信息。  如果没有开通，是没有办法测试支付的。

**Comment by TonyYule** [comment]
能不能把请求列表 给一个 谢谢

**Comment by kongzhidea** [comment]
这个懒的搞了额，
我把controller 列出来，

这是微信支付：
 https://github.com/kongzhidea/pay/tree/master/pay/src/main/java/com/kk/pay/weixin/controller
里面有 扫码，h5支付，查询订单，退款等。

这个是支付宝支付：
https://github.com/kongzhidea/pay/tree/master/pay/src/main/java/com/kk/pay/alipay/controller
里面有 扫码，h5支付，查询订单，退款等。


具体链接接只能自己拼接了，

还有微信 网页支付，也叫公众号支付，需要在微信公众号 预先设置  支付路径才可以， 只有此支付路径才可以调起微信支付，支付宝没有这个限制。

**Comment by 472405746** [comment]
可以集成微信小程序不？
